
package com.innoprise.cashreceipt.userws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CashreceiptUserWSService", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/", wsdlLocation = "http://localhost:8080/CashreceiptUserWSService/CashreceiptUserWS?wsdl")
public class CashreceiptUserWSService
    extends Service
{

    private final static URL CASHRECEIPTUSERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CASHRECEIPTUSERWSSERVICE_EXCEPTION;
    private final static QName CASHRECEIPTUSERWSSERVICE_QNAME = new QName("http://ejb.userws.cashreceipt.innoprise.com/", "CashreceiptUserWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CashreceiptUserWSService/CashreceiptUserWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CASHRECEIPTUSERWSSERVICE_WSDL_LOCATION = url;
        CASHRECEIPTUSERWSSERVICE_EXCEPTION = e;
    }

    public CashreceiptUserWSService() {
        super(__getWsdlLocation(), CASHRECEIPTUSERWSSERVICE_QNAME);
    }

    public CashreceiptUserWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CASHRECEIPTUSERWSSERVICE_QNAME);//, features);
    }

    public CashreceiptUserWSService(URL wsdlLocation) {
        super(wsdlLocation, CASHRECEIPTUSERWSSERVICE_QNAME);
    }

    public CashreceiptUserWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CASHRECEIPTUSERWSSERVICE_QNAME);//, features);
    }

    public CashreceiptUserWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CashreceiptUserWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);//, features);
    }

    /**
     * 
     * @return
     *     returns CashreceiptUserWS
     */
    @WebEndpoint(name = "CashreceiptUserWSPort")
    public CashreceiptUserWS getCashreceiptUserWSPort() {
        return super.getPort(new QName("http://ejb.userws.cashreceipt.innoprise.com/", "CashreceiptUserWSPort"), CashreceiptUserWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CashreceiptUserWS
     */
    @WebEndpoint(name = "CashreceiptUserWSPort")
    public CashreceiptUserWS getCashreceiptUserWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.userws.cashreceipt.innoprise.com/", "CashreceiptUserWSPort"), CashreceiptUserWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CASHRECEIPTUSERWSSERVICE_EXCEPTION!= null) {
            throw CASHRECEIPTUSERWSSERVICE_EXCEPTION;
        }
        return CASHRECEIPTUSERWSSERVICE_WSDL_LOCATION;
    }

}
