
package com.innoprise.cashreceipt.userws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CashreceiptUserWS", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CashreceiptUserWS {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/", className = "com.innoprise.cashreceipt.userws.client.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/", className = "com.innoprise.cashreceipt.userws.client.GetUsersResponse")
    @Action(input = "http://ejb.userws.cashreceipt.innoprise.com/CashreceiptUserWS/getUsersRequest", output = "http://ejb.userws.cashreceipt.innoprise.com/CashreceiptUserWS/getUsersResponse")
    public List<Object> getUsers();

    /**
     * 
     * @param userName
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserRoleGroups", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/", className = "com.innoprise.cashreceipt.userws.client.GetUserRoleGroups")
    @ResponseWrapper(localName = "getUserRoleGroupsResponse", targetNamespace = "http://ejb.userws.cashreceipt.innoprise.com/", className = "com.innoprise.cashreceipt.userws.client.GetUserRoleGroupsResponse")
    @Action(input = "http://ejb.userws.cashreceipt.innoprise.com/CashreceiptUserWS/getUserRoleGroupsRequest", output = "http://ejb.userws.cashreceipt.innoprise.com/CashreceiptUserWS/getUserRoleGroupsResponse")
    public List<Object> getUserRoleGroups(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

}
